CREATE TABLE IF NOT EXISTS leads (
  id              SERIAL PRIMARY KEY,
  phone           VARCHAR(20) UNIQUE NOT NULL,
  name            VARCHAR(255),
  source          VARCHAR(50) DEFAULT 'whatsapp',
  status          VARCHAR(30) DEFAULT 'active',
  birth_date      VARCHAR(20),
  height          VARCHAR(10),
  weight          VARCHAR(10),
  profession      VARCHAR(255),
  smoker          VARCHAR(10),
  income          VARCHAR(100),
  cpf             VARCHAR(20),
  scheduled       BOOLEAN DEFAULT FALSE,
  scheduled_at    TIMESTAMPTZ,
  followup_status INT DEFAULT 0,
  last_ia_message TIMESTAMPTZ,
  last_lead_message TIMESTAMPTZ,
  has_lead_replied BOOLEAN DEFAULT FALSE,
  rd_contact_id   VARCHAR(100),
  rd_deal_id      VARCHAR(100),
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);
